# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sign_in(object):
    def setupUi(self, sign_in):
        sign_in.setObjectName("sign_in")
        sign_in.resize(581, 431)
        sign_in.setStyleSheet("background-color: #524b4b;")
        self.centralwidget = QtWidgets.QWidget(sign_in)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1_login.setGeometry(QtCore.QRect(150, 270, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_1_login.setFont(font)
        self.pushButton_1_login.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: #7d7a7a;\n"
"    border: 2px solid #fc8383;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: #fc8383;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #ff4545;\n"
"    color: black;\n"
"}\n"
"")
        self.pushButton_1_login.setObjectName("pushButton_1_login")
        self.label_1_login = QtWidgets.QLabel(self.centralwidget)
        self.label_1_login.setGeometry(QtCore.QRect(20, 80, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_1_login.setFont(font)
        self.label_1_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_login.setStyleSheet("color: white;")
        self.label_1_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_login.setObjectName("label_1_login")
        self.label_2_login = QtWidgets.QLabel(self.centralwidget)
        self.label_2_login.setGeometry(QtCore.QRect(140, 20, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2_login.setFont(font)
        self.label_2_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2_login.setStyleSheet("color: white;")
        self.label_2_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_login.setObjectName("label_2_login")
        self.lineEdit_1_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1_login.setGeometry(QtCore.QRect(80, 140, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_1_login.setFont(font)
        self.lineEdit_1_login.setStyleSheet("border-radius: 10px;\n"
"background-color: white;\n"
"color: black;")
        self.lineEdit_1_login.setText("")
        self.lineEdit_1_login.setObjectName("lineEdit_1_login")
        self.lineEdit_2_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2_login.setGeometry(QtCore.QRect(80, 200, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2_login.setFont(font)
        self.lineEdit_2_login.setStyleSheet("border-radius: 10px;\n"
"background-color: white;\n"
"color: black;")
        self.lineEdit_2_login.setObjectName("lineEdit_2_login")
        self.pushButton_2_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_login.setGeometry(QtCore.QRect(150, 350, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2_login.setFont(font)
        self.pushButton_2_login.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: #7d7a7a;\n"
"    border: 2px solid #fc8383;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: #fc8383;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #ff4545;\n"
"    color: black;\n"
"}\n"
"")
        self.pushButton_2_login.setObjectName("pushButton_2_login")
        sign_in.setCentralWidget(self.centralwidget)

        self.retranslateUi(sign_in)
        QtCore.QMetaObject.connectSlotsByName(sign_in)

    def retranslateUi(self, sign_in):
        _translate = QtCore.QCoreApplication.translate
        sign_in.setWindowTitle(_translate("sign_in", "Authorization"))
        self.pushButton_1_login.setText(_translate("sign_in", "Вхід у програм"))
        self.label_1_login.setText(_translate("sign_in", "Введіть логін та пароль для входу"))
        self.label_2_login.setText(_translate("sign_in", "Авторизація користувача"))
        self.lineEdit_1_login.setPlaceholderText(_translate("sign_in", "логін\\почта"))
        self.lineEdit_2_login.setPlaceholderText(_translate("sign_in", "пароль"))
        self.pushButton_2_login.setText(_translate("sign_in", "Зареєструвати"))